### ISSUE TITLE
Crash loading apkg

### ISSUE THREAD

**Issue by Queuecumber** [mattstraehl/AmgiNori#1]
I tried twice to load the apkg you linked on Reddit and the app crashed both times. Let me know if I can provide more information

**Comment by mattstraehl** [comment]
Thanks a lot for reporting the issue. What file manager do you use to locate the file? And what Android version?

**Comment by Queuecumber** [comment]
I'm using the latest official Android N beta with the ASUS ZenUI file manager ([this thing](https://play.google.com/store/apps/details?id=com.asus.filemanager&hl=en))

**Comment by mattstraehl** [comment]
Great, I'm able to reproduce it, will fix it with the next release. Thanks again.

**Comment by Queuecumber** [comment]
고마워요, let me know if I can help any further

**Comment by mattstraehl** [comment]
The issue should be fixed with version 1.3.1.
